#!/usr/bin/env bash
# Print Render dashboard env vars from local pipeline/config.yaml (secrets stay on your machine).
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
CFG="$ROOT/pipeline/config.yaml"
EX="$ROOT/pipeline/config.example.yaml"
SRC="$CFG"
[[ -f "$SRC" ]] || SRC="$EX"

python3 - "$SRC" <<'PY'
import sys, yaml
cfg = yaml.safe_load(open(sys.argv[1]))
tg = cfg.get("telegram") or {}
node = cfg.get("node") or {}
print("=== Set these in Render Dashboard (both 2hotatl-relay and 2hotatl-pipeline) ===")
print(f"TELEGRAM_BOT_TOKEN={tg.get('bot_token','')}")
print(f"TELEGRAM_CHANNEL_ID={tg.get('channel_id','')}")
edit = node.get("edit_key") or "pick-a-long-random-admin-key"
print(f"ADMIN_EDIT_KEY={edit}")
print(f"NODE_EDIT_KEY={edit}")
print("")
print("PIPELINE_WORKER_SECRET is auto-generated by render.yaml envVarGroups.")
print("Deploy: https://dashboard.render.com → New → Blueprint → alvinemon/sapp")
PY
